version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "customer:1:1,zoneA:1:1,zoneB:1:1,zoneC:1:1,zoneD:1:1"
    volumes:
      - kafka-data:/var/run/docker.sock
volumes:
  postgres-data:
  kafka-data:
