{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "interview.serviceAccountName" . }}
  labels:
{{ include "interview.labels" . | nindent 4 }}
{{- end -}}
